/**
 * 타로 도메인: 메이저 아르카나 핵심 상징 (결과 해석 참조용)
 */

export const TAROT_MAJOR_MEANINGS = {
  ko: [
    '0 바보: 새로운 시작, 순수, 모험',
    '1 마법사: 의지, 창조, 행동',
    '2 여사제: 직관, 비밀, 내면의 목소리',
    '3 여제: 풍요, 양육, 자연',
    '4 황제: 구조, 권위, 안정',
    '5 교황: 전통, 영성, 가르침',
    '6 연인: 선택, 사랑, 조화',
    '7 전차: 의지력, 승리, 통제',
    '8 힘: 용기, 인내, 내면의 힘',
    '9 은둔자: 성찰, 지혜, 고독',
    '10 운명의 수레바퀴: 순환, 변화, 운명',
    '11 정의: 공정, 균형, 진실',
    '12 매달린 사람: 포기, 관점 전환, 희생',
    '13 사신: 종료, 변형, 새 시작',
    '14 절제: 조화, 인내, 균형',
    '15 악마: 유혹, 속박, 물질',
    '16 탑: 붕괴, 깨달음, 갑작스러운 변화',
    '17 별: 희망, 영감, 치유',
    '18 달: 불안, 직관, 무의식',
    '19 태양: 성공, 기쁨, 명료',
    '20 심판: 부활, 소명, 판단',
    '21 세계: 완성, 통합, 성취',
  ],
  en: [
    '0 Fool: New beginning, innocence, adventure',
    '1 Magician: Will, creation, action',
    '2 High Priestess: Intuition, mystery, inner voice',
    '3 Empress: Abundance, nurture, nature',
    '4 Emperor: Structure, authority, stability',
    '5 Hierophant: Tradition, spirituality, teaching',
    '6 Lovers: Choice, love, harmony',
    '7 Chariot: Willpower, victory, control',
    '8 Strength: Courage, patience, inner strength',
    '9 Hermit: Introspection, wisdom, solitude',
    '10 Wheel of Fortune: Cycle, change, destiny',
    '11 Justice: Fairness, balance, truth',
    '12 Hanged Man: Surrender, shift of perspective, sacrifice',
    '13 Death: End, transformation, new beginning',
    '14 Temperance: Harmony, patience, balance',
    '15 Devil: Temptation, bondage, materialism',
    '16 Tower: Collapse, revelation, sudden change',
    '17 Star: Hope, inspiration, healing',
    '18 Moon: Anxiety, intuition, unconscious',
    '19 Sun: Success, joy, clarity',
    '20 Judgement: Revival, calling, judgement',
    '21 World: Completion, integration, achievement',
  ],
  ja: [
    '0 愚者: 新たな始まり、純粋さ、冒険',
    '1 魔術師: 意志、創造、行動',
    '2 女教皇: 直感、神秘、内なる声',
    '3 女帝: 豊かさ、養育、自然',
    '4 皇帝: 構造、権威、安定',
    '5 教皇: 伝統、スピリチュアリティ、教え',
    '6 恋人: 選択、愛、調和',
    '7 戦車: 意志力、勝利、コントロール',
    '8 力: 勇気、忍耐、内なる力',
    '9 隠者: 内省、知恵、孤独',
    '10 運命の輪: 循環、変化、運命',
    '11 正義: 公平、バランス、真実',
    '12 吊られた男: 手放し、視点の転換、犠牲',
    '13 死神: 終わり、変容、新たな始まり',
    '14 節制: 調和、忍耐、バランス',
    '15 悪魔: 誘惑、束縛、物質主義',
    '16 塔: 崩壊、啓示、突然の変化',
    '17 星: 希望、インスピレーション、癒し',
    '18 月: 不安、直感、無意識',
    '19 太陽: 成功、喜び、明晰',
    '20 審判: 復活、使命、判断',
    '21 世界: 完成、統合、達成',
  ],
};
